// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwhtuapxzavsekpyucce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aHR1YXB4emF2c2VrcHl1Y2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTU3MTYsImV4cCI6MjA3MTQzMTcxNn0.4fCqeFYIHjvXEJ1g5meEHTUzUeXQyX6kjSXWudsuCbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});